### PR TITLE
support vehicle_angular_velocity

### PR DESCRIPTION
**Pull request by dagar**
Placeholder/reminder for supporting `vehicle_angular_velocity` in PX4 (https://github.com/PX4/Firmware/pull/12596)

TODO
 - support new vehicle_angular_velocity without breaking existing usage of vehicle_attitude rollspeed/pitchspeed/yawspeed and rate_ctrl_status rollspeed/pitchspeed/yawspeed.

 - https://github.com/PX4/flight_review/blob/f9d1247f73c5cc5386b8bfeedbfe135a85ae0f5f/plot_app/configured_plots.py#L144
 - https://github.com/PX4/flight_review/blob/f9d1247f73c5cc5386b8bfeedbfe135a85ae0f5f/plot_app/configured_plots.py#L120-L122

### CODE REVIEW

**Comment by dagar** [comment]
Waiting on https://github.com/PX4/Firmware/pull/12596.

**Comment by bkueng** [comment]
Can you please finish this as you already merged the Firmware PR?

**Comment by dagar** [comment]
Sorry for the delay, hoping to get back to this tomorrow. There were a couple areas where handling compatibility got a bit messy.

**Comment by dagar** [comment]
I've grouped most of it, although it could be further simplified.

**Comment by bkueng** [comment]
Squashed, further simplified and merged.

**Pull request closed without merging**
