### PR TITLE
Tailsitter : correct rate setpoint to match rate for tailsitter

### PR DESCRIPTION
**Pull request by ciresimo**
I was analysing some logs for a quadtailsitter without control surfaces that i'm developing, and I notice that even though the angle tracking of roll was quite good, the plots for the rates did not make sense
Screenshot from 2024-03-21 13-51-43
rollrate_wrong

Here the [complete logs](https://review.px4.io/plot_app?log=d21b119d-21dc-45b4-9380-481d8e2cf5cb) for reference 
By looking into the `configured_plots.py` I saw that if the vehicle is a tailsitter angles and rates are reassigned to be plotted in a more consisten way for the instants that drone is flying in fixed wing:

- yaw -> -roll
- roll -> yaw

but this is not applied to the rates setpoint, so the result is that on the rollrate plot , for example , the data shown are:

- in MC 

1. Roll rate
2. Roll rate setpoint

- in FW

1.  Inverse of yaw rate
2. Roll rate setpoint

What I did was simply remapping also the setpoints in fixed wing so to have in the same plot
- in FW

1.  Inverse of yaw rate
2.  Inverse of yaw rate setpoint
rollrate_new

Tracking is still not perfect, but that's a problem with the simluation.
Aslo plot of yaw rate makes more sense:

- Old
yawrate_wrong

- New
yawrate_new

Honestly this to me was very confusing, since I tried to find a reason for the behavior of correct angles but completely wrong rate control. In this way it makes more sense, so you could easily see if the rate controller is good at tracking. I think this was the way it was handled in the past, since I saw some old logs review that did not have this problem and I think is related on the new control approach.
I'm conscious that the code may need other adjustments, since probably I'm not considering some cases (did not look into PID analysis for now). I opened this PR just to understand if this was actually a problem or the was a specific reason for this

### CODE REVIEW

**Comment by ciresimo** [comment]
@sfuhrer can you give some feedback on this?

**Comment by khikmatovfarkhod** [comment]
@sfuhrer please let us know if this is true. the rates for roll, pitch and yaw don't make sense

**Comment by sfuhrer** [comment]
Makes total sense to also transform the rate setpoints and not only the rate measurements from the body to the "fixed-wing" frame :+1:

**Review by sfuhrer — CHANGES_REQUESTED** [review]
I agree with the necessity of the change, thanks for handling it!
Can you check the CI failures?

**Comment by ciresimo** [comment]
I think I had some problems with pyulog. I rebased and now seems to be fine
I ran the test locally and got 10

**Review by sfuhrer — APPROVED** [review]
Thanks!

**Review by bkueng — APPROVED** [review]

**Pull request merged**
