### PR TITLE
plots: show flight mode labels when hovering over the plot

### PR DESCRIPTION
**Pull request by bkueng**
- currently on certain (low quality?) screens, some of the flight mode
  colors are hard to distinguish
- all the Auto modes had only a single color, i.e. it was not possible to
  distinguish between Mission, RTL or Land.

Disadvantage: for certain logs, the plots start to look overloaded.

Examples:

bokeh_plot 1
bokeh_plot 2
bokeh_plot 3
Extreme case:
bokeh_plot

### CODE REVIEW

**Comment by joaeba** [comment]
great work Beat. Would it be possible to include a button that disables all hover labels in case a plot gets to cluttered?

**Comment by dagar** [comment]
Very helpful!

**Comment by MaEtUgR** [comment]
Good idea!

**Comment by bkueng** [comment]
> Would it be possible to include a button that disables all hover labels in case a plot gets to cluttered?

Possible yes, but I'd like to avoid adding buttons, as it does not necessarily improve user experience.

Let's merge it then.

**Pull request merged**
