### PR TITLE
Add list of public log files

### PR DESCRIPTION
**Pull request by bkueng**
This adds a simple list with all public log files from flight reports. It is fully sortable & searchable. Flight report uploaders retain the option to keep the log private.
The goals are:
- simple way to keep track of log files
- make it easy to validate what & how much a specific SW/HW has been tested
- a way to provide access to log files to everyone

flight_review_browse_logs

It currently sends the whole list to the browser. Should this become an issue, we can switch to server-side processing, as the used library DataTables allows to do so.

@kd0aij

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Nice! How hard would it be to summarise air-time per board / vehicle class / release?

**Comment by bkueng** [comment]
Should be fairly simple. I was thinking about adding charts, but we need data for this.

**Comment by LorenzMeier** [comment]
Charts would indeed be nice. And one nitpick: The aviation term is "pilot error", not "pilot mistake".

**Comment by kd0aij** [comment]
This looks very nice, and will provide the necessary info for both assessment and direction of flight test coverage. 

Observations: 
* Flight test 2: description conflicts with flight modes
* Would be nice to have a release tag in addition to the SHA for SW version
* air-time per flight mode would also be nice

**Comment by LorenzMeier** [comment]
@bkueng does the server update automatically?

**Comment by bkueng** [comment]
@kd0aij 
> Flight test 2: description conflicts with flight modes

That's really only my local sample, with log files I had around :)

> Would be nice to have a release tag in addition to the SHA for SW version

I'll look into that (It's because I only ever use master or feature branches)

> air-time per flight mode would also be nice

Agree, I just don't want to overload the table. Maybe I'll add it to the accumulated results.

@LorenzMeier: I just did. I want to avoid that for now, it could easily break (for example now, I needed to upgrade the DB, or it might need manual config updates, ...)

**Pull request merged**
