### PR TITLE
plots: Change the plot colors

### PR DESCRIPTION
**Pull request by zehortigoza**
Right now looking at the plot of Raw Radio Control Inputs I can not
see a difference between Channel 2 and Channel 3.
So changing to more different colors to improve readability.

### CODE REVIEW

**Comment by zehortigoza** [comment]
bokeh_plot
This is waayy better to read.

**Comment by bkueng** [comment]
This is too saturated and does not fit together with the other colors (yes I'm picky). How about this:
```
colors8 = [colors3[0], colors3[1], colors3[2], '#333333', '#999999', '#e58C33',
        '#33e5e5', '#e533e5']
```
bokeh_plot
bokeh_plot 1

**Comment by zehortigoza** [comment]
Sounds better than the actual color so I'm fine.

**Comment by bkueng** [comment]
Done: https://github.com/PX4/flight_review/commit/c0acdc1eed80b96358447e1dd5060b97e7809cdb

**Pull request closed without merging**
